# https://github.com/libbpf/libbpf-rs/blob/master/.github/workflows/audit.yml
name: Audit

on:
  schedule:
    - cron: '10 0 * * 1' # At 10am on Monday

jobs:
  cargo-deny:
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v1
      with:
        command: check ${{ matrix.checks }}
